app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/controllers/listings_controller.rb
app/controllers/pages_controller.rb
app/views/pages/_form.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
test/controllers/listings_controller_test.rb

Also search by category that will send a query of the search. In additon the navbar now sends to home.
I also touched upon the index action of the listings (just to receive the query) so now @listings is either the search query's listings or all if there is no search query (or empty string)

Made home page with all listings at bottom

---

Gemfile
Gemfile.lock
db/seeds.rb

Created Seed

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/listings/_show.scss
app/controllers/listings_controller.rb
app/views/listings/show.html.erb
config/routes.rb
test/controllers/listing_controller_test.rb

Made listings page (needs a lot of work)

Listing page

---

app/controllers/account/bookings_controller.rb
app/controllers/application_controller.rb
app/views/account/bookings/index.html.erb
app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20191124141704_add_first_name_to_user.rb
db/migrate/20191124141719_add_last_name_to_user.rb
db/schema.rb
db/seeds.rb
test/controllers/account/bookings_controller_test.rb

made user login and dashboard very simple

made user functionality

---

app/views/listings/show.html.erb
db/migrate/20191124142208_add_description_to_listings.rb
db/schema.rb

Added description migration 
Also made some small changes to listing page

added description migration

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_filterbar.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_searchbar.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/listings/_index.scss
app/controllers/listings_controller.rb
app/views/listings/index.html.erb
config/routes.rb
test/controllers/listings_controller_test.rb

Added a searchbar ('guests' should be deleted)
Added a filterbar (not functional yet)
Added listings (design will be changed)
Added map picture (to be changed to real map)
To do: add card clickable and redirect to 'show' page.

searchbar filterbar listing-cards map-pic

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/listings/_index.scss

Just some playing with scrollbar, will figure out later

playing with scrolling

---

Gemfile
Gemfile.lock
app/controllers/account/bookings_controller.rb
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/listings_controller.rb
app/policies/account/bookings_policy.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/listing_policy.rb
test/policies/account/bookings_policy_test.rb
test/policies/booking_policy_test.rb
test/policies/listing_policy_test.rb

I added the authorization for the dashboad, show page, search page, home page

Adding Pundit Authorization for basic web actions

---

app/controllers/listings_controller.rb
app/policies/listing_policy.rb
app/views/account/bookings/index.html.erb
app/views/listings/show.html.erb
db/schema.rb

Show page also features listing's photo now

added authorization for new listing

---

.gitignore
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_forms.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/listings/_index.scss
app/assets/stylesheets/listings/_show.scss
app/models/booking.rb
app/views/listings/index.html.erb
app/views/listings/show.html.erb
db/migrate/20191125104630_add_time_to_bookings.rb
db/migrate/20191125105446_change_time_in_bookings.rb
db/schema.rb

So far i've made the page layout.
Will change the pics to uploaded ones + add map + fix main container, cause it's not central and aligned weirdly.

page layout with form + time added

---

app/models/user.rb
db/schema.rb

made default photo for user avatar

---

app/assets/stylesheets/listings/_index.scss
app/controllers/reviews_controller.rb
app/views/listings/index.html.erb
test/controllers/reviews_controller_test.rb

Reviews controller with index, create, destroy

Reviews Controller

---

db/seeds.rb

added description to office breakroom

Added missing description to office breakroom

---

app/models/listing.rb

category validation array

---

app/javascript/packs/application.js
app/javascript/packs/homepage.js
app/views/pages/home.html.erb

makes icons bigger when hovering

made home icons increase decrease

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/listings/_show.scss
app/controllers/reviews_controller.rb
app/models/listing.rb
app/models/review.rb
app/views/listings/index.html.erb
app/views/listings/show.html.erb
app/views/pages/_form.html.erb
app/views/pages/home.html.erb
db/seeds.rb

Changed reviews controller and model validations/associations.
Rating is shown everywhere (trying to figure out how to add empty stars).
Reviews are shown (will do the 'new review' form tomorrow).
Also seeded several fake reviews.

reviews and rating added

---

app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/views/listings/show.html.erb
package.json
yarn.lock

Now when choosing a date there is a calender

added flatpickr to show page for booking

---

app/views/listings/index.html.erb
app/views/listings/show.html.erb
app/views/pages/home.html.erb

Made the stars full or empty based on the rating

Stars respond to rating with full and empty

---

app/controllers/listings_controller.rb
app/controllers/reviews_controller.rb
app/models/review.rb
app/policies/review_policy.rb
app/views/listings/show.html.erb
config/routes.rb

Drew routes for reviews
Added validations/simplified code in review.rb
Added ‘render listing/show’

Added leave review form for listings

---

app/javascript/components/price.js
app/javascript/packs/application.js
app/views/listings/show.html.erb

Fixed the total price to reflect hours to book

Responsive total price

---

app/controllers/account/bookings_controller.rb
app/controllers/bookings_controller.rb
app/models/booking.rb
app/models/listing.rb
app/models/user.rb
app/policies/account/bookings_policy.rb
app/views/account/bookings/pending_bookings.html.erb
app/views/listings/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20191126064835_add_requested_and_booked_to_bookings.rb
db/migrate/20191126093825_remove_requested_from_bookings.rb
db/schema.rb

accept decline

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

the icons are all fake but they look good

created footer

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/views/layouts/application.html.erb

fixed footer

---

app/assets/stylesheets/listings/_show.scss
app/views/account/bookings/pending_bookings.html.erb
app/views/listings/show.html.erb
app/views/shared/_footer.html.erb
db/seeds.rb

Seed updates

---

db/seeds.rb

fixed images in users seed

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/listings/_show.scss
app/views/listings/index.html.erb
app/views/listings/show.html.erb
app/views/pages/home.html.erb

Added avatars to the show page and reviews, also added some comments to make the show page easier to read

avatars on show page and reviews

---

app/assets/stylesheets/listings/_show.scss
app/views/listings/show.html.erb

changed background and icons on showpage

Show page fix

---

app/assets/stylesheets/listings/_index.scss

made preview image round and text black

improved photo uploader

---

app/assets/stylesheets/listings/_index.scss
app/views/account/bookings/edit_user.html.erb

avatar is round, listing photos are not

fixed mistake on photo uploader
